Feature/create iconbutton
Pet-projects-CodePET/Frontend pull request #20
Opened 2024-02-07 22:40 UTC by makc-anisimov

### Сделал разметку кнопки IconButton с указанием типа через пропсы
**Пример:** 
`<IconButton variant="git" size="desktop" />`

2024-02-08 08:07 UTC, makc-anisimov commented
размер убрал из пропсов и реализовал через media-выражение

2024-02-08 21:58 UTC, makc-anisimov commented
добавил новый пропс: ссылку для кнопки

+создал виджет iconButtonList и поместил туда все четыре кнопки

2024-02-09 08:12 UTC, Julia-Papina approved these changes

2024-02-09 09:30 UTC, Liolikmolo requested changes
Думаю надо перенести в entities

2024-02-09 09:30 UTC, Liolikmolo commented on src/widgets/iconButtonList/index.ts
Я бы все-таки пока не ложил это в widget. Здесь скорее подходит entities, потому что widget это уже готовое что-то с логикой. А entities - это просто оболочка, в которую мы будем вставлять эти иконки. Потом, когда для каждой иконки подключится фича, уже тогда они будут в составе какого-либо виджета.

2024-02-10 11:23 UTC, Liolikmolo approved these changes

2024-02-10 11:41 UTC, merged