feat(input): add input component
Pet-projects-CodePET/Frontend pull request #31
Opened 2024-02-11 17:03 UTC by vvkon13

* добавлен компонент input

2024-02-12 11:39 UTC, Liolikmolo requested changes

2024-02-12 11:39 UTC, Liolikmolo commented on src/shared/ui/input/input.tsx
По нашей договоренности (общий эксель) нужно переписать именованную функцию на function declaration. Я эту настройку добавил в линтер, дальше будет проверять автоматом)

2024-02-12 14:57 UTC, DBKai commented on src/shared/style/variables.scss
> +$--Foreground-subtle: #94a3b8;
subtitle?

2024-02-12 15:18 UTC, vvkon13 commented on src/shared/style/variables.scss
> +$--Foreground-subtle: #94a3b8;
Ага. Как в первоисточнике - в Figme.

2024-02-12 15:19 UTC, vvkon13 commented on src/shared/style/variables.scss
> +$--Foreground-subtle: #94a3b8;
Там subtle

2024-02-12 15:44 UTC, VanVorobyov commented on src/shared/style/variables.scss
> +$--Foreground-subtle: #94a3b8;
Опечатка)

2024-02-12 20:06 UTC, Liolikmolo approved these changes

2024-02-13 08:32 UTC, Julia-Papina approved these changes

2024-02-13 09:03 UTC, merged

2024-02-13 15:36 UTC, DBKai commented on src/shared/ui/input/input.module.scss
> +    font-family: Open Sans;
font-family: Open Sans. Здесь 2 слова, отделенных пробелом. Наверное лучше в одинарные кавычки заключить. А еще лучше вынести в переменную.